version: "3.5"

volumes:
  postgres-data:
  redis-data:

services:
  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: always

  backend:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: ["make", "dev_server"]
    env_file:
      - ./.env
    ports:
      - 3334:3334
    volumes:
      - /opt/node_modules
      - .:/opt
    restart: always
    depends_on:
      - postgres
      - redis
